# Generated by Django 4.1.5 on 2023-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='register_date',
            field=models.DateTimeField(),
        ),
    ]
